
# Heuristic map from import name -> PyPI distribution name for common cases
# Extend as needed.
IMPORT_TO_DIST = {
    "PIL": "Pillow",
    "cv2": "opencv-python",
    "sklearn": "scikit-learn",
    "bs4": "beautifulsoup4",
    "yaml": "PyYAML",
    "Crypto": "pycryptodome",
    "yaml": "PyYAML",
    "lxml": "lxml",
    "ujson": "ujson",
    "orjson": "orjson",
    "tomli": "tomli",
    "tomllib": "tomllib",  # stdlib in 3.11+, keep for older pins
    "IPython": "ipython",
    "jupyter": "jupyter",
    "notebook": "notebook",
    "tensorflow": "tensorflow",
    "tf_keras": "tf-keras",
    "torch": "torch",
    "torchvision": "torchvision",
    "torchaudio": "torchaudio",
    "jax": "jax",
    "jaxlib": "jaxlib",
    "cupy": "cupy-cuda11x",
    "pymongo": "pymongo",
    "psycopg2": "psycopg2-binary",
    "pymysql": "pymysql",
    "mysqlclient": "mysqlclient",
    "sqlalchemy": "SQLAlchemy",
    "fastapi": "fastapi",
    "uvicorn": "uvicorn",
    "starlette": "starlette",
    "django": "Django",
    "flask": "Flask",
    "jinja2": "Jinja2",
    "pydantic": "pydantic",
    "requests": "requests",
    "httpx": "httpx",
    "matplotlib": "matplotlib",
    "seaborn": "seaborn",
    "numpy": "numpy",
    "pandas": "pandas",
    "scipy": "scipy",
    "tqdm": "tqdm",
    "rich": "rich",
    "typer": "typer",
}
